import Head from 'next/head'
import Navbar from '<prefi>/components/Navbar/Navbar'
import DtExperience from '<prefi>/components/DtExperience/DtExperience'
import Footer from '<prefi>/components/Footer/Footer'
import HeroSection from '<prefi>/components/Home/HeroSection'
import PlayerExp from '<prefi>/components/JugExperience/PlayerExp'



export default function Home() {
  return (
    <>
      <Head>
        <title>Daniel Hugo Lopez</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Navbar />
      <HeroSection />
      <DtExperience />
      <PlayerExp />
      <Footer />


    </>
  )
}
